# AWS Configuration
aws:
  region: us-east-1
  s3:
    bucket: lovely-docs-2024-aba1a952-0384-45a3-87db-73f525b62b92
    prefixes:
      - "1225"
      - "26192"
#      - "279534"
#      - "279451"

# Pinecone Configuration
pinecone:
  index_name: medical-records18
  dimension: 768  # BioBERT dimension

# Data Processing
data_processing:
  chunk_size: 512  # Maximum text length for BERT input
  batch_size: 100  # Batch size for processing and Pinecone uploads

# Model Paths
models:
  ner: "samrawal/bert-base-uncased_clinical-ner"
  bert: "medicalai/ClinicalBERT"
  zero_shot: "facebook/bart-large-mnli"

# Entity Extraction
entity_extraction:
  ner_confidence_threshold: 0.5
  yake:
    max_ngram_size: 3
    num_keywords: 20
# Logging
logging:
  level: INFO
  file: logs/process.log

# Search Criteria
search_criteria:
  afff_exposure:
    keywords:
      - AFFF
      - firefighting foam
      - PFAS
    occupations:
      - firefighter
      - military personnel
    date_range:
      start: 1970-01-01
      end: 2023-12-31
  bard_powerport:
    keywords:
      - Bard PowerPort
      - implantable port
      - catheter fracture
    conditions:
      - blood stream infection
      - port fracture
    date_range:
      start: 2024-01-01
      end: 2024-10-22  # Set to null for no end date
# Global scoring system configuration
scoring_system:
  version: "1.0"
  min_score: 0
  max_score: 100
  
  # Configuration for confidence levels
  confidence_levels:
    very_high:
      threshold: 80
      description: "Strong evidence supporting diagnosis"
    high:
      threshold: 60
      description: "Substantial evidence supporting diagnosis"
    moderate:
      threshold: 40
      description: "Moderate evidence supporting diagnosis"
    low:
      threshold: 20
      description: "Limited evidence supporting diagnosis"
    very_low:
      threshold: 0
      description: "Insufficient evidence for diagnosis"

  # Weight distribution for different components
  component_weights:
    symptom_specificity: 0.35
    rarity_score: 0.25
    evidence_tiers: 0.25
    procedures: 0.15

# Disease-specific configurations
diseases:
  # Template for each disease
  template:
    categories:
      Symptoms:
        weight: 1.0
        required: true
      LabResultsRedFlags:
        weight: 0.9
        required: false
      OtherThingsToLookFor:
        weight: 0.6
        required: false
      DiagnosticProcedures:
        weight: 0.8
        required: false
      Complications:
        weight: 0.7
        required: false
      TreatmentOptions:
        weight: 0.3
        required: false

    # Specificity weights for different types of findings
    specificity_weights:
      very_high: 0.9
      high: 0.7
      moderate: 0.5
      low: 0.3
      very_low: 0.1

    # Population frequency adjustments
    frequency_adjustments:
      very_rare: 0.9    # <1% in population
      rare: 0.7        # 1-5% in population
      uncommon: 0.5    # 5-10% in population
      common: 0.3      # 10-25% in population
      very_common: 0.1 # >25% in population

    # Evidence tier configuration
    evidence_tiers:
      must_have:
        weight: 1.0
        min_required: 1
      strong_support:
        weight: 0.8
        min_required: 0
      moderate_support:
        weight: 0.6
        min_required: 0
      weak_support:
        weight: 0.3
        min_required: 0

  # Example specific disease configuration (Kidney Cancer)
  KidneyCancer:
    inherits: template  # Inherits base template
    
    # Override specific weights for kidney cancer
    categories:
      Symptoms:
        high_specificity:
          - "Blood in urine (hematuria)"
          - "Mass or lump in abdomen/side"
        moderate_specificity:
          - "Low back pain on one side"
          - "Unexplained weight loss"
        low_specificity:
          - "Fatigue"
          - "Fever"
          - "Loss of appetite"
          - "High blood pressure"
      
      LabResultsRedFlags:
        must_have:
          - "Elevated creatinine"
          - "Abnormal urinalysis"
        strong_support:
          - "Anemia"
          - "Elevated calcium levels"
        moderate_support:
          - "Elevated liver enzymes"
          - "Elevated C-reactive protein"
      
      DiagnosticProcedures:
        required:
          - "CT scan of abdomen and pelvis"
          - "MRI of abdomen"
        confirmatory:
          - "Renal biopsy"
        supporting:
          - "Ultrasound of kidneys"
          - "Renal angiography"
      
      Complications:
        critical:
          - "Metastasis"
        severe:
          - "Chronic kidney disease"
          - "Paraneoplastic syndromes"
        moderate:
          - "Venous thromboembolism"
          - "Hypercalcemia"

    # Disease-specific scoring adjustments
    scoring_adjustments:
      age_factor:
        under_40: 0.8
        40_to_60: 1.0
        over_60: 1.2
      
      risk_factors:
        smoking: 1.3
        family_history: 1.4
        obesity: 1.2
        hypertension: 1.1

    # Minimum criteria for valid score
    minimum_criteria:
      required_categories:
        - "Symptoms"
        - "LabResultsRedFlags"
      minimum_symptoms: 2
      minimum_lab_flags: 1
      
# Scoring system parameters
parameters:
  time_window_days: 365  # Look back period for symptoms
  min_occurrence: 2      # Minimum occurrences of a symptom
  severity_threshold: 0.6 # Minimum severity score to consider
  confidence_interval: 0.95 # Required confidence level for scoring

# Scoring weights
scoring:
  similarity_weight: 0.5
  entity_match_weight: 0.3
  date_relevance_weight: 0.2

# Metadata Configuration
metadata:
  text_limit: 100  # Limit for 'text' field in characters
  entity_limit: 5  # Limit for number of entities per type
  max_size: 39000  # Maximum metadata size in bytes (40KB)
  MAX_METADATA_SIZE: 40000  # Maximum metadata size in bytes (40KB)
